### ISSUE TITLE
Cert and key permissions 

### ISSUE THREAD

**Issue by trexxeon** [gregtwallace/certwarden-client#1]
I’ve been trying to set permissions with environment variables 

CW_CLIENT_KEY_PERM		CW_CLIENT_CERT_PERM

but how are these supposed to be set? Simply putting =0644 or =644 give the file wrong permissions.

also on a different subject, can one instance get multiple certificates and put them in different locations? As it is now i have set up multiple instances for pulling multiple certs

**Comment by gregtwallace** [comment]
I think the permissions thing is a bug that I'll need to figure out the best way to address.

Regarding key/cert - the client supports one pair. Can you detail your specific use case for multiple key/cert on one box client?

**Comment by trexxeon** [comment]
> Regarding key/cert - the client supports one pair. Can you detail your specific use case for multiple key/cert on one box client?

For example I have one box running traefik, authelia and emby. One traefik instant hosts multiple domains.

So I want multiple domain certificates.
So 
*.wildcard-public-domain1.com
*.wildcard-public-domain2.com
auth.public-domain3.com

this is just an example, but the feature to be able to download multiple domains would be nice. Even tough I have set up multiple instances of certwarden-client in a stack and that works as well.

**Comment by gregtwallace** [comment]
Noted. 

I think this would add more complexity than I'd like when the intention is a home lab or small environment. I will keep this in mind for a possible future change though. Glad you are able to use it with multiple containers. Hopefully the resource footprint is still pretty small that way. :)

I will try to get the permissions fixed soon.
