### ISSUE TITLE
Support for native run and native script

### ISSUE THREAD

**Issue by LeGmask** [gregtwallace/certwarden-client#2]
Firstly, it's a really nice work !
I wonder if we could adapt the client in order to be able to run it outside a docker compose. Also, It would be cool if we can run shell script after instead of just restarting a container.

**Comment by gregtwallace** [comment]
Docker compose isn't actually required. Or do you mean to have a non-containerized version?

**Comment by gregtwallace** [comment]
Idle / Unclear of exact request.

**Comment by LeGmask** [comment]
> Docker compose isn't actually required. Or do you mean to have a non-containerized version?

I was thinking of a non-containerized version with a systemd service or something like so.
And running some native commands such as a `systemctl restart ...` is something really important I think especially if you do not use docker on your server (yeah there's some you cannot use docker :sweat_smile: )

**Comment by gregtwallace** [comment]
I don't really intend to build this outside of a container, as it doesn't serve my use case.

There is at least one other project that might be better suited to your needs: https://certwarden-deploy.adora.codes/

Note: I haven't actually used this, someone just mentioned it to me recently.
