### ISSUE TITLE
main/main.go:16	failed to configure app (CW_CLIENT_AES_KEY_BASE64 AES key is not 32 bytes long)

### ISSUE THREAD

**Issue by darwincr** [gregtwallace/certwarden-client#3]
This page
https://www.certwarden.com/docs/using_certificates/client/

seems to imply the value CW_CLIENT_AES_KEY_BASE64 is not required

But when i tried running the docker command it says it is required

> $ /usr/bin/docker run --name certwardenclient \
>   -p 5055:5055 \
>   -v /var/run/docker.sock:/var/run/docker.sock \
>   -v /persist/certwardenclient/certs:/opt/certwarden/certs \
>   -e TZ=America/New_York \
>   -e CW_CLIENT_FILE_UPDATE_TIME_START='04:30' \
>   -e CW_CLIENT_FILE_UPDATE_TIME_END='05:45' \
>   -e CW_CLIENT_FILE_UPDATE_DAYS_OF_WEEK='' \
>   -e CW_CLIENT_RESTART_DOCKER_CONTAINER0='LibreChat' \
>   -e CW_CLIENT_SERVER_ADDRESS='https://cw.domain.net' \
>   -e CW_CLIENT_KEY_NAME='chat.domain.net' \
>   -e CW_CLIENT_KEY_APIKEY='xxxxxxxxxxxxxxxxxxxx' \
>   -e CW_CLIENT_CERT_NAME='chat.domain.net' \
>   -e CW_CLIENT_CERT_APIKEY='xxxxxxxxxxxxxxxxxxxx' \
>   ghcr.io/gregtwallace/certwarden-client:latest
> 2024-12-18T03:43:58.872-0500	info	main/config.go:148	starting Cert Warden Client v0.3.1
> 2024-12-18T03:43:58.872-0500	fatal	main/main.go:16	failed to configure app (CW_CLIENT_AES_KEY_BASE64 AES key is not 32 bytes long)

this page 
https://github.com/gregtwallace/certwarden-client/blob/main/pkg/main/config.go

says this:

> CW_CLIENT_AES_KEY_BASE64  - base64 raw url encoding of AES key used for communication between server and client (generate one on server)

I cant figure out where on the server i can generate this key

**Comment by darwincr** [comment]
Found it
is under the certificate itself
 post processing > Cert Warden Client

**Comment by gregtwallace** [comment]
Thanks. I've updated the site to fix the omission.
